# This is a basic workflow to help you get started with Actions

name: deploy-to-firebase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup node js
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install

      # Build and export
      - name: Build
        run: npm build
      # Archive
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      # Restore
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs
      # Deploy
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
